#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WinFormApp")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMenuType(MenuType instance);
    partial void UpdateMenuType(MenuType instance);
    partial void DeleteMenuType(MenuType instance);
    partial void InsertMenus(Menus instance);
    partial void UpdateMenus(Menus instance);
    partial void DeleteMenus(Menus instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WinFormApp.Properties.Settings.Default.WinFormAppConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MenuType> MenuTypes
		{
			get
			{
				return this.GetTable<MenuType>();
			}
		}
		
		public System.Data.Linq.Table<Menus> Menus
		{
			get
			{
				return this.GetTable<Menus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuType")]
	public partial class MenuType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _menuType1;
		
		private string _menuTypeName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmenuType1Changing(System.Nullable<int> value);
    partial void OnmenuType1Changed();
    partial void OnmenuTypeNameChanging(string value);
    partial void OnmenuTypeNameChanged();
    #endregion
		
		public MenuType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="menuType", Storage="_menuType1", DbType="Int")]
		public System.Nullable<int> menuType1
		{
			get
			{
				return this._menuType1;
			}
			set
			{
				if ((this._menuType1 != value))
				{
					this.OnmenuType1Changing(value);
					this.SendPropertyChanging();
					this._menuType1 = value;
					this.SendPropertyChanged("menuType1");
					this.OnmenuType1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuTypeName", DbType="VarChar(50)")]
		public string menuTypeName
		{
			get
			{
				return this._menuTypeName;
			}
			set
			{
				if ((this._menuTypeName != value))
				{
					this.OnmenuTypeNameChanging(value);
					this.SendPropertyChanging();
					this._menuTypeName = value;
					this.SendPropertyChanged("menuTypeName");
					this.OnmenuTypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menus")]
	public partial class Menus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMenu;
		
		private System.Nullable<int> _idParentMenu;
		
		private string _MenuType;
		
		private string _MenuName;
		
		private System.Nullable<int> _MenuOrder;
		
		private string _Description;
		
		private string _Url;
		
		private string _icon;
		
		private System.Nullable<bool> _NewWindow;
		
		private System.Nullable<int> _LeftExtent;
		
		private System.Nullable<int> _RightExtent;
		
		private bool _Status;
		
		private string _MenuFunction;
		
		private string _PageName;
		
		private string _MenuTransact;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMenuChanging(int value);
    partial void OnidMenuChanged();
    partial void OnidParentMenuChanging(System.Nullable<int> value);
    partial void OnidParentMenuChanged();
    partial void OnMenuTypeChanging(string value);
    partial void OnMenuTypeChanged();
    partial void OnMenuNameChanging(string value);
    partial void OnMenuNameChanged();
    partial void OnMenuOrderChanging(System.Nullable<int> value);
    partial void OnMenuOrderChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OniconChanging(string value);
    partial void OniconChanged();
    partial void OnNewWindowChanging(System.Nullable<bool> value);
    partial void OnNewWindowChanged();
    partial void OnLeftExtentChanging(System.Nullable<int> value);
    partial void OnLeftExtentChanged();
    partial void OnRightExtentChanging(System.Nullable<int> value);
    partial void OnRightExtentChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    partial void OnMenuFunctionChanging(string value);
    partial void OnMenuFunctionChanged();
    partial void OnPageNameChanging(string value);
    partial void OnPageNameChanged();
    partial void OnMenuTransactChanging(string value);
    partial void OnMenuTransactChanged();
    #endregion
		
		public Menus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMenu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idMenu
		{
			get
			{
				return this._idMenu;
			}
			set
			{
				if ((this._idMenu != value))
				{
					this.OnidMenuChanging(value);
					this.SendPropertyChanging();
					this._idMenu = value;
					this.SendPropertyChanged("idMenu");
					this.OnidMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idParentMenu", DbType="Int")]
		public System.Nullable<int> idParentMenu
		{
			get
			{
				return this._idParentMenu;
			}
			set
			{
				if ((this._idParentMenu != value))
				{
					this.OnidParentMenuChanging(value);
					this.SendPropertyChanging();
					this._idParentMenu = value;
					this.SendPropertyChanged("idParentMenu");
					this.OnidParentMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MenuType
		{
			get
			{
				return this._MenuType;
			}
			set
			{
				if ((this._MenuType != value))
				{
					this.OnMenuTypeChanging(value);
					this.SendPropertyChanging();
					this._MenuType = value;
					this.SendPropertyChanged("MenuType");
					this.OnMenuTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MenuName
		{
			get
			{
				return this._MenuName;
			}
			set
			{
				if ((this._MenuName != value))
				{
					this.OnMenuNameChanging(value);
					this.SendPropertyChanging();
					this._MenuName = value;
					this.SendPropertyChanged("MenuName");
					this.OnMenuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuOrder", DbType="Int")]
		public System.Nullable<int> MenuOrder
		{
			get
			{
				return this._MenuOrder;
			}
			set
			{
				if ((this._MenuOrder != value))
				{
					this.OnMenuOrderChanging(value);
					this.SendPropertyChanging();
					this._MenuOrder = value;
					this.SendPropertyChanged("MenuOrder");
					this.OnMenuOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="VarChar(200)")]
		public string icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				if ((this._icon != value))
				{
					this.OniconChanging(value);
					this.SendPropertyChanging();
					this._icon = value;
					this.SendPropertyChanged("icon");
					this.OniconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWindow", DbType="Bit")]
		public System.Nullable<bool> NewWindow
		{
			get
			{
				return this._NewWindow;
			}
			set
			{
				if ((this._NewWindow != value))
				{
					this.OnNewWindowChanging(value);
					this.SendPropertyChanging();
					this._NewWindow = value;
					this.SendPropertyChanged("NewWindow");
					this.OnNewWindowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeftExtent", DbType="Int")]
		public System.Nullable<int> LeftExtent
		{
			get
			{
				return this._LeftExtent;
			}
			set
			{
				if ((this._LeftExtent != value))
				{
					this.OnLeftExtentChanging(value);
					this.SendPropertyChanging();
					this._LeftExtent = value;
					this.SendPropertyChanged("LeftExtent");
					this.OnLeftExtentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightExtent", DbType="Int")]
		public System.Nullable<int> RightExtent
		{
			get
			{
				return this._RightExtent;
			}
			set
			{
				if ((this._RightExtent != value))
				{
					this.OnRightExtentChanging(value);
					this.SendPropertyChanging();
					this._RightExtent = value;
					this.SendPropertyChanged("RightExtent");
					this.OnRightExtentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuFunction", DbType="VarChar(500)")]
		public string MenuFunction
		{
			get
			{
				return this._MenuFunction;
			}
			set
			{
				if ((this._MenuFunction != value))
				{
					this.OnMenuFunctionChanging(value);
					this.SendPropertyChanging();
					this._MenuFunction = value;
					this.SendPropertyChanged("MenuFunction");
					this.OnMenuFunctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="VarChar(100)")]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this.OnPageNameChanging(value);
					this.SendPropertyChanging();
					this._PageName = value;
					this.SendPropertyChanged("PageName");
					this.OnPageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuTransact", DbType="VarChar(120)")]
		public string MenuTransact
		{
			get
			{
				return this._MenuTransact;
			}
			set
			{
				if ((this._MenuTransact != value))
				{
					this.OnMenuTransactChanging(value);
					this.SendPropertyChanging();
					this._MenuTransact = value;
					this.SendPropertyChanged("MenuTransact");
					this.OnMenuTransactChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
